### ISSUE TITLE
Should hiredis dependency be in 'devDependencies'?

### ISSUE THREAD

**Issue by johanbrook** [NodeRedis/node-redis-parser#9]
Hi! I'm using this package through the Bull npm package, and am getting some build warnings when requiring Bull in my app:

```
Unable to resolve some modules:

  "hiredis" in app/node_modules/redis-parser/lib/hiredis.js
(os.osx.x86_64)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save hiredis
```

(using Meteor, but I don't think that's relevant).

It seems like you're specifying your `hiredis` dependency as a `devDependency`, and then [requiring it here](https://github.com/NodeRedis/node-redis-parser/blob/master/lib/hiredis.js#L3), and thus the app fails to build, since it doesn't install dev dependencies?

Let me know if I'm off here.

**Comment by BridgeAR** [comment]
The dependency is correct in the dev dependencies. You have to require it [explicitly](https://github.com/NodeRedis/node-redis-parser/blob/master/lib/parser.js#L258) and it'll fall back to the js parser if not installed. The issue is, that the meteor build process does not check that but tries to resolve the require directly.

**Comment by johanbrook** [comment]
Gotcha, thanks for the swift reply. I'll bring the problem with the Meteor devs.

Thanks!
